services:
  web:
    image: ghcr.io/martingruzno/privatebin:v1.0.2
    env_file:
      - ./.env
    restart: unless-stopped
    read_only: true
    user: "65534:82"  # Run the container with the UID:GID of your Docker user
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./privatebin-data:/srv/data
      - ./var:/srv/notifications:ro
      # - ./tpl:/srv/tpl
      # - ./lib:/srv/lib
